{% set name = "cartogram" %}
{% set version = "1.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81ed9fa1c5b68d9c8cb7b96a9c3676e1830f71e1dc4ca765ce432a37e19b55e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - joblib
    - numpy
    - pandas
    - shapely

test:
  imports:
    - cartogram
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.com/austromorph/python-cartogram
  summary: Compute continous cartograms (anamorphic maps)
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - christophfink
